### ISSUE TITLE
Реализовать функции для работы с брокером

### ISSUE THREAD

**Issue by map82top** [map82top/db_management_Course_work#13]
В отличии от трейдера брокер создается без счетов
Счета создаются при добавления брокера к маркету
Все ассайны брокеров к маркету хранятся в следующем отношении (**КодБрокера**, **КодМаркета**. НомерСчета)

- Создания брокера
- Добавления брокера на маркет
- Удаления брокера с маркета с закрытием его счета
- Удаления брокера (с удалением всех его привязок к маркетам)

**Comment by altavelor** [comment]
Связана с #14
